<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2A8DDC6" failures="0" tests="5" name="Restasuree.RestApi.Manageing" time="1.777" errors="1" timestamp="2023-07-03T12:48:47 IST" skipped="4">
  <testcase classname="Restasuree.RestApi.Manageing" name="Groupdata" time="1.777">
    <error message="JSONObject[&quot;name&quot;] not found." type="org.json.JSONException">
      <![CDATA[org.json.JSONException: JSONObject["name"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at Restasuree.RestApi.Manageing.Groupdata(Manageing.java:120)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Groupdata -->
  <system-out/>
  <testcase classname="Restasuree.RestApi.Manageing" name="geting">
    <skipped/>
  </testcase> <!-- geting -->
  <system-out/>
  <testcase classname="Restasuree.RestApi.Manageing" name="puting">
    <skipped/>
  </testcase> <!-- puting -->
  <system-out/>
  <testcase classname="Restasuree.RestApi.Manageing" name="books">
    <skipped/>
  </testcase> <!-- books -->
  <system-out/>
  <testcase classname="Restasuree.RestApi.Manageing" name="put">
    <skipped/>
  </testcase> <!-- put -->
  <system-out/>
</testsuite> <!-- Restasuree.RestApi.Manageing -->
